### Logowanie 
POST http://localhost:5270/api/Auth/login
Content-Type: application/json

{
  "email": "operator@parkingsystem.pl",
  "password": "SecureOperator2026!"
}

###

### Pobieranie danych o mnie (Chroniony endpoint)
GET http://localhost:5270/api/Auth/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJQYXJraW5nU3lzdGVtU1BBIiwiaXNzIjoiUGFya2luZ1N5c3RlbUFQSSIsImV4cCI6MTc4MDY5NzY4NSwibmJmIjoxNzgwNjk0MDg1LCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6IjIzYmFmZGE3LTQzOTQtNDQ0YS1iM2IxLTg5NjdiOWJmODcyMiIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL2VtYWlsYWRkcmVzcyI6Im9wZXJhdG9yQHBhcmtpbmdzeXN0ZW0ucGwiLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9naXZlbm5hbWUiOiJQaW90ciIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL3N1cm5hbWUiOiJOb3dhayIsInN0YXR1cyI6IkFjdGl2ZSIsImp0aSI6ImJjY2JkNmRhLTg3OWQtNGZlNy05MDFhLWM2ZDEyYzIxNjI5MCIsImlhdCI6MTc4MDY5NDA4NSwiaHR0cDovL3NjaGVtYXMubWljcm9zb2Z0LmNvbS93cy8yMDA4LzA2L2lkZW50aXR5L2NsYWltcy9yb2xlIjoiT3BlcmF0b3IifQ.DcLhs5OC0q8lZbMnHZ-uzsPPq6rQUt3ITGwjPp0uxEw